### ISSUE TITLE
it doesnt work!!!!!!1

### ISSUE THREAD

**Issue by hexservice** [XConnect24/depot-sinjoh#1]
it doesnt work on my wii and now i have the big **sad** :( :((((( i cant read coronavirus news on news chanel riiconnect24 better!!!1111 😭 😭😭 https://www.youtube.com/watch?v=z97qLNXeAMQ i think the owner stans bts that is why!! 👎 💯 pls fix ur service!!112!

**Comment by Oscie57** [comment]
100 gecs

**Comment by hexservice** [comment]
bts

**Comment by TMinusBlastedRocket** [comment]
Note: change IQ variable to something >100 as opposed to the current 6

**Comment by hexservice** [comment]
its actually 4 fyi

**Comment by TMinusBlastedRocket** [comment]
We're screwed

**Comment by hexservice** [comment]
ok i will close this now

**Comment by SketchMaster2001** [comment]
lmao how did this get so much traction

**Comment by zurgeg** [comment]
> 
> 
> lmao how did this get so much traction

 @SketchMaster2001 I assume you did this lo-

**Comment by 6100m** [comment]
:brr See, this is why we should have deleted the repo. It was a mess to begin with, me learning a bunch of new coding lanugages.

Also why was I banned from the organization? Kind of confused.

**Comment by zurgeg** [comment]
> 
> 
> :brr See, this is why we should have deleted the repo. It was a mess to begin with, me learning a bunch of new coding lanugages.
> 
> Also why was I banned from the organization? Kind of confused.

this issue was a joke...
